Sceys/Models/Expediente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sceys.Models
{
    public class Expediente
    {
        [Key]
        public int ExpedienteId { get; set; }             

        public int AprendizId { get; set; }        

        public DateTime Fecha { get; set; }

        public int Estado { get; set; }

        public string descripcionQueja { get; set;}

        //Se relaciona con     
        public virtual Aprendiz Aprendiz { get; set; }              

        //Se relaciona en:
        public virtual ICollection<Falta> Faltas { get; set; }

        public virtual ICollection<RecepcionDocumento> RecepcionDocumentos { get; set; }

        public virtual ICollection<Documentacion> Documentacions { get; set; }
    }
}

Sceys/Models/modelsView/ExpedienteView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sceys.Models
{
    public class ExpedienteView
    {
        public int ExpedienteId { get; set; }

        public string documento { get; set; }

        public string aprendiz { get; set; }

        public string documentoAprendiz { get; set;}

        public string documentoReceptor { get; set; }

        public string contacto { get; set; }

        public DateTime fecha { get; set; }

        public int estado { get; set; }

        public string descripcionGeneral { get; set; }

        public int tipoFaltaId { get; set; }

        public int calificacionId { get; set; }

        public string descripcionFalta { get; set; }
        
        public string descripcionQueja { get; set; }
    }
}

Sceys/Controllers/ExpedientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Sceys.Models;
using Sceys.Models.modelsView;
using System.Web;
using System.IO;

namespace Sceys.Controllers
{
    public class ExpedientesController : Controller
    {
        private SceysContext db = new SceysContext();

        // GET: Expedientes
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {

                //tipos de falta por defecto
                this.LlenarTipoFalta("Académica", "");
                this.LlenarTipoFalta("Disciplinaria", "");
                this.LlenarTipoFalta("Académica y Disciplinaria", "");

                //calificación por defecto para cada tipo de falta
                this.LlenarCalificacion("Leve");
                this.LlenarCalificacion("Grave");
                this.LlenarCalificacion("Gravisima");

                //guardar cambios en la base de datos
                try
                {
                    db.SaveChanges();
                }
                catch (Exception msg)
                {
                    TempData["Errors"] = msg.Message;
                    return RedirectToAction("Index", "Home");
                }

                var expedientes = (from Aprendiz in db.Aprendizs
                                   join Persona in db.Personas on Aprendiz.PersonaId equals Persona.PersonaId
                                   join Expediente in db.Expedientes on Aprendiz.AprendizId equals Expediente.AprendizId
                                   orderby Expediente.Estado ascending

                                   select new ExpedienteView
                                   {
                                       ExpedienteId = Expediente.ExpedienteId,
                                       documento = Persona.Documento,
                                       aprendiz = Persona.PrimerNombre + " " + Persona.SegundoNombre + " " + Persona.PrimerApellido + " " + Persona.SegundoNombre,
                                       contacto = Persona.Correo,
                                       fecha = Expediente.Fecha,
                                       estado = Expediente.Estado,
                                       descripcionQueja = Expediente.descripcionQueja
                                   }).OrderBy(p => p.estado).ThenBy(p => p.fecha);

                return View(expedientes);
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Expedientes/Details/5
        public ActionResult Details(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                /*
                    * La primera parte para ver los detalles del expediente de un aprendiz
                    * consiste en realizar la consulta de la información que se encuentra
                    * en las distintas tablas que se relacionan con la tabla Expedientes
                */

                // Se consulta el Expediente del aprendiz
                var expediente = db.Expedientes.Find(id);
                if (expediente == null)
                {
                    return HttpNotFound();
                }

                //Se consulta la información del aprendiz. En este caso, el nombre del aprendiz.
                var aprendiz = (
                    from Aprendiz in db.Aprendizs
                    join Expediente in db.Expedientes on Aprendiz.AprendizId equals Expediente.AprendizId
                    join Persona in db.Personas on Aprendiz.PersonaId equals Persona.PersonaId
                    where Expediente.ExpedienteId == id
                    select new
                    {
                        documento = Persona.Documento,
                        nombre = Persona.PrimerNombre + " " + Persona.SegundoNombre + " " + Persona.PrimerApellido + " " + Persona.SegundoApellido,
                        correo = Persona.Correo,
                        ficha = Aprendiz.Ficha,
                        programa = (from programaxcentro in db.ProgramaCentros
                                    join Aprendix in db.Aprendizs on programaxcentro.ProgramaCentroId equals Aprendix.ProgramaCentroId
                                    join programa in db.Programas on programaxcentro.ProgramaId equals programa.ProgramaId
                                    where Aprendix.PersonaId == Persona.PersonaId
                                    select programa.Nombre
                                          ).FirstOrDefault()
                    }
                    ).FirstOrDefault();

                //Se consulta el tipo de falta que tiene el aprendiz, desde la tabla TipoFalta
                var tipoFalta = (
                            from Falta in db.Faltas
                            join TipoFalta in db.TipoFaltas on Falta.TipoFaltaId equals TipoFalta.TipoFaltaId
                            join Expediente in db.Expedientes on Falta.ExpedienteId equals Expediente.ExpedienteId
                            where Expediente.ExpedienteId == id
                            select TipoFalta.Nombre
                           ).FirstOrDefault();

                //Se consulta calificación de la falta que tiene el aprendiz, desde la tabla CalificacionFalta
                var calificacionFalta = (
                    from Falta in db.Faltas
                    join Calificacion in db.Calificacions on Falta.CalificacionId equals Calificacion.CalificacionId
                    join Expediente in db.Expedientes on Falta.ExpedienteId equals Expediente.ExpedienteId
                    where Expediente.ExpedienteId == id
                    select Calificacion.Descripcion
                    ).FirstOrDefault();

                //Se consulta de la tabla Faltas, la descripción de la normatividad
                var DescripcionFaltas = (
                from Falta in db.Faltas
                join Expediente in db.Expedientes on Falta.ExpedienteId equals Expediente.ExpedienteId
                where Expediente.ExpedienteId == id
                select Falta.DescripcionFaltas
                           ).FirstOrDefault();

                //Se llenan los campos que serán mostrados en la vista con las consultas previas que se hicieron.
                var fecha = Convert.ToString(expediente.Fecha);
                var expedientes = new ExpedienteDetailsView
                {
                    ExpedienteId = expediente.ExpedienteId,
                    documentoAprendiz = aprendiz.documento,
                    nombreAprendiz = aprendiz.nombre,
                    correoAprendiz = aprendiz.correo,
                    fichaAprendiz = aprendiz.ficha,
                    programaAprendiz = aprendiz.programa,
                    fecha = fecha,
                    Estado = expediente.Estado,
                    descripcionQueja = expediente.descripcionQueja,
                    tipoFalta = tipoFalta,
                    calificacionFalta = calificacionFalta,
                    DescripcionFaltas = DescripcionFaltas
                };

                return View(expedientes);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Expedientes/Create
        public ActionResult Create()
        {

            //Valores para los DropDownList
            ViewBag.Nombre = new SelectList(db.TipoFaltas, "TipoFaltaId", "Nombre");
            ViewBag.Descripcion = new SelectList(db.Calificacions, "CalificacionId", "Descripcion");

            //Información de los capítulos del reglamento del aprendiz
            ViewBag.Capitulo = new SelectList(db.Capitulos, "CapituloId", "Descripcion");

            return View();

        }

        // POST: Expedientes/Create
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(ExpedienteView expedienteView, List<RecepcionDocumento> datos)
        {
            return Json(0, JsonRequestBehavior.AllowGet);
        }

        // GET: Expedientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Expediente expediente = db.Expedientes.Find(id);
                if (expediente == null)
                {
                    return HttpNotFound();
                }
                ViewBag.AprendizId = new SelectList(db.Aprendizs, "AprendizId", "Ficha", expediente.AprendizId);
                //ViewBag.InformanteId = new SelectList(db.Informantes, "InformanteId", "Descripcion", expediente.InformanteId);
                //ViewBag.RecepcionDocumentoId = new SelectList(db.RecepcionDocumentoes, "RecepcionDocumentoId", "RecepcionDocumentoId", expediente.RecepcionDocumentoId);
                return View(expediente);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Expedientes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Estado")] Expediente expediente)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(expediente).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");

Sceys/Views/Expedientes/Delete.cshtml
@model Sceys.Models.Expediente

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Expediente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aprendiz.Ficha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aprendiz.Ficha)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Informante.Descripcion)*@
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Informante.Descripcion)*@
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.RecepcionDocumento.RecepcionDocumentoId)*@
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.RecepcionDocumento.RecepcionDocumentoId)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Volver", "Index")
        </div>
    }
</div>

Sceys/Views/Expedientes/Details.cshtml
@model Sceys.Models.modelsView.ExpedienteDetailsView

@{
    ViewBag.Title = "Detalles";
}

<link href="~/Content/sceys/main.css" rel="stylesheet" />

<br />
<!--Mapa de navegación-->
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li>
                    <i class="glyphicon glyphicon-home"></i> <a href="@Url.Action("About", "Home")" class="alink">Inicio</a>
                </li>
                <li class="">
                    <i class="fa fa-stethoscope"></i> Expedientes
                </li>
                <li class="active">
                    <i class="glyphicon glyphicon-list-alt"></i> Detalles
                </li>
            </ol>
        </div>
    </div>
</div>

<!--Detalles de los Expedientes-->
<!--Nuevo Expediente-->
<div class="panel panel-primary">
    <div class="panel-heading">Detalles del Expediente</div>
    <div class="panel-body">

        <!--Información General del expediente-->
        <div class="panel panel-info">
            <div class="panel-heading">Información General</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4">
                        <label>Documento del aprendiz</label>
                        @Html.EditorFor(model => model.documentoAprendiz, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                    <div class="col-lg-4">
                        <label>Nombre del aprendiz</label>
                        @Html.EditorFor(model => model.nombreAprendiz, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                    <div class="col-lg-4">
                        <label>Correo</label>
                        @Html.EditorFor(model => model.correoAprendiz, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>
                <div class="row">
                    <br />
                    <div class="col-md-4">
                        <label>Ficha</label>
                        @Html.EditorFor(model => model.fichaAprendiz, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                    <div class="col-lg-4">
                        <label>Programa de Formación</label>
                        @Html.EditorFor(model => model.programaAprendiz, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                    <div class="col-lg-4">
                        <label>Fecha registro de queja</label>
                        @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                </div>
                <div class="row">
                    <br />
                    <div class="col-lg-4">
                        <label>Tipo de Falta</label>
                        @Html.EditorFor(model => model.tipoFalta, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                    <div class="col-lg-4">
                        <label>Calificación de la falta</label>
                        @Html.EditorFor(model => model.calificacionFalta, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </div>
                    <div class="col-lg-4">
                    </div>
                </div>
                <div class="row dDescripcion">
                    <br />
                    <div class="col-md-12 dDescripcion1">
                        <label>Descripción</label>
                        @Html.TextAreaFor(model => model.descripcionQueja, new { @rows = "10", @class = "form-control descripcion", @readonly = "readonly" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <!--Guardar información en base de datos-->
        <div class="row">
            <div class="col-md-12 btn-group">
                <center>
                    <button type="button" id="pdf" name="pdf" class="btn btn-info">Queja en PDF</button>
                </center>
            </div>
        </div>
    </div>
</div>

<div class="pull-left">
    <ul class="pager">
        <li>@Html.ActionLink("Editar", "Edit", new { id = Model.ExpedienteId })</li>
        <li>@Html.ActionLink("Volver", "Index")</li>
    </ul>
</div>

<!--Scripts-->
<!--Searchs-->
<script src="~/Scripts/sceys/ExpedienteManagerController.js"></script>

<!--Make PDFs-->
<script src="~/Scripts/pdfmake/pdfmake.min.js"></script>
<script src="~/Scripts/pdfmake/vfs_fonts.js"></script>
<script src="~/Scripts/sceys/PdfManagerController.js"></script>

Sceys/Views/Expedientes/Edit.cshtml
@model Sceys.Models.Expediente

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expediente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ExpedienteId)

        <div class="form-group">
            @Html.LabelFor(model => model.InformanteId, "InformanteId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("InformanteId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InformanteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AprendizId, "AprendizId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AprendizId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AprendizId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecepcionDocumentoId, "RecepcionDocumentoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RecepcionDocumentoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RecepcionDocumentoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sceys/Views/Expedientes/adjuntarDocumentacion.cshtml
@model Sceys.Models.modelsView.ExpedienteAdjuntarDocumentacionView
@{
    ViewBag.Title = "Adjuntar Documentacion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--Styles-->
<link href="~/Content/sceys/main.css" rel="stylesheet" />
<link href="~/Content/sceys/dataTable.css" rel="stylesheet" />

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <ol class="breadcrumb">
                <li>
                    <i class="glyphicon glyphicon-home"></i> <a href="@Url.Action("About", "Home")" class="alink">Inicio</a>
                </li>
                <li class="">
                    <i class="fa fa-stethoscope"></i> Expedientes
                </li>
                <li class="active">
                    <i class="glyphicon glyphicon-plus"></i> Quejas
                </li>
            </ol>
        </div>
    </div>
</div>

<!--Nuevo Expediente-->
<div class="panel panel-primary">
    <div class="panel-heading">Documentación Queja</div>
    <div class="panel-body">
        @using (Html.BeginForm("registrarQuejaInstructor", "Expedientes", FormMethod.Post, new { id = "frm-registrarQueja", name = "frm-adjuntarDocumentacion", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <!--Adjuntar archivos-->
            <div class="panel panel-info">
                <div class="panel-heading">Adjuntar Archivos</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4">
                            <label>Expediente #</label>
                            @Html.EditorFor(model => model.ExpedienteId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                         </div>
                        <div class="col-lg-4">
                            <label>Fecha de Creación</label>
                            @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="col-lg-4">
                            <label>Estado</label>
                            @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                    </div>
                    <div class="row">
                        <br />
                        <div class="col-md-4">
                            <label>Documento del aprendiz</label>
                            @Html.EditorFor(model => model.documentoAprendiz, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="col-lg-4">
                            <label>Nombre del aprendiz</label>
                            @Html.EditorFor(model => model.nombreAprendiz, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="col-lg-4">
                            <label>Correo</label>
                            @Html.EditorFor(model => model.correoAprendiz, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                    </div>
                    <div class="row">
                        <br />
                        <div class="col-md-12">
                            <label>Descripción</label>
                            <textarea id="comentarioDocumentoAdjunto" name="comentarioDocumentoAdjunto" class="form-control comentarioDocumentoAdjunto" rows="2" placeholder="Describa y justifique por qué adjunta el documento a la queja"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <br />
                        <div class="col-md-12">
                            <div id="custom-search-input">
                                <div class="input-group col-md-12">
                                    <input type="file" id="archivo" name="archivo" class="search-query form-control archivo" placeholder="Buscar Expediente" />
                                    <span class="input-group-btn">
                                        <button class="btn btn-danger" type="submit">
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }

        <!--Archivos Adjuntos-->
        <div class="panel panel-info">
            <div class="panel-heading">Archivos adjuntos</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 pull-left table-responsive">
                        <table id="tblIndex" name="tblIndex" class="table table-hover tblIndex">
                            <thead>
                                <tr class="">
                                    <th></th>
                                    <th>Archivo adjunto</th>
                                    <th>Descripcion</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!--Scrips-->
<script src="~/Scripts/sceys/dataTable.js"></script>
<script src="~/Scripts/sceys/ExpedientesController.js"></script>
<script src="~/Scripts/sceys/Manager.js"></script>